-- AlterTable
ALTER TABLE `parsemethod` MODIFY `state` ENUM('DRAFT', 'READY_PUB', 'PUBLISHED') NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE `post` MODIFY `state` ENUM('DRAFT', 'READY_PUB', 'PUBLISHED') NOT NULL DEFAULT 'DRAFT';
